<?php

/**
 * @file
 * Module file for Node Example module.
 *
 * Part of the Examples for Developers project.
 */

/**
 * @defgroup external_link_d7 Example: Node
 * @ingroup examples
 * @{
 * Example defining a node type in code.
 *
 * This is an example outlining how a module can be used to define a new
 * node type. Our example node type will allow users to specify multiple
 * "colors", a "quantity" and an "image" for their nodes; some kind of
 * rudimentary inventory-tracking system, perhaps?
 *
 * The basic pattern for defining a node type is to tell Drupal about the
 * node's fields and view modes. Drupal will then take over and manage
 * the storage for this node type. This differs from Drupal 6, where we
 * would have to handle all the database storage ourselves in the module.
 *
 * Remember that most node types do not require any custom code, as one
 * simply creates them using the Drupal user interface. Creating a node like
 * this in code is a special case.
 *
 * At absolute minimum, in order to provide a content type for
 * node, you have to implement hook_node_info() and hook_form().
 * Node can take care of the rest, if you want it to.
 *
 * First and foremost, defining a node type happens in
 * hook_node_info(). Our implementation of this hook gives
 * Drupal an array of information about the content type
 * we want to create.
 *
 * Next, since we want to add fields to our content type, we
 * implement hook_node_type_insert(), which gives us a chance
 * to modify recently-created content types.
 *
 * Drupal is able to handle deletion of our content, including
 * dependencies based on re-use of our field instances, so we don't
 * have to manage any of it.
 *
 * In previous versions of Drupal, "teaser" and "page" were node view modes.
 * In Drupal 7 we can define custom view modes to let the node know how it
 * should return it's data.  This module declares a custom view mode called
 * "external_link_d7_list".
 *
 * Consult the @link http://drupal.org/node/707832 Field API Tutorial @endlink
 * and @link http://drupal.org/node/443536 Field API Handbook Page @endlink
 * and @link field Field API documentation @endlink.
 *
 * @see field_example.module
 */

/**
 * Implements hook_menu().
 *
 * We are providing a default page to illustrate the use of our custom node view
 * mode that will live at http://example.com/?q=examples/external_link_d7
 */
function external_link_d7_menu() {
  $items['examples/external_link_d7'] = array(
    'page callback' => 'external_link_d7_page',
    'access arguments' => array('access content'),
    'title' => 'Node Example',
  );
  return $items;
}

/**
 * Implements hook_node_info().
 *
 * We use hook_node_info() to define our node content type.
 */
function external_link_d7_node_info() {
  // We define the node type as an associative array.
  return array(
    'external_link_d7' => array(
      'name' => t('External Link Page'),
      // 'base' tells Drupal the base string for hook functions.
      // This is often the module name; if base is set to 'mymodule',
      // Drupal would call mymodule_insert() or similar for node
      // hooks. In our case, the base is 'external_link_d7'.
      'base' => 'external_link_d7',
      'description' => t('This is an external link page for content on the site that when viewed redirects to an external url.'),
      'title_label' => t('Link Title'),
      // We'll set the 'locked' attribute to TRUE, so users won't be
      // able to change the machine name of our content type.
      'locked' => TRUE,
    ),
  );
}

/**
 * Implements hook_node_type_insert().
 *
 * Much like hook_node_insert() lets us know that a node is being
 * inserted into the database, hook_node_type_insert() lets us know
 * that a new content type has been inserted.
 *
 * Since Drupal will at some point insert our new content type,
 * this gives us a chance to add the fields we want.
 *
 * It is called for all inserts to the content type database, so
 * we have to make sure we're only modifying the type we're
 * concerned with.
 */
function external_link_d7_node_type_insert($content_type) {
  if ($content_type->type == 'external_link_d7') {
    // First we add the body field. Node API helpfully gives us
    // node_add_body_field().
    // We'll set the body label now, although we could also set
    // it along with our other instance properties later.
    $body_instance = node_add_body_field($content_type, t('Link Description'));

    // Add our external_link_d7_list view mode to the body instance
    // display by instructing the body to display as a summary.
    $body_instance['display']['external_link_d7_list'] = array(
      'label' => 'hidden',
      'type' => 'text_summary_or_trimmed',
    );

    // Save our changes to the body field instance.
    field_update_instance($body_instance);

    // Create all the fields we are adding to our content type.
    foreach (_external_link_d7_installed_fields() as $field) {
      field_create_field($field);
    }

    // Create all the instances for our fields.
    foreach (_external_link_d7_installed_instances() as $instance) {
      $instance['entity_type'] = 'node';
      $instance['bundle'] = 'external_link';
      field_create_instance($instance);
    }
  }
}

/**
 * Implements hook_form().
 *
 * Drupal needs for us to provide a form that lets the user
 * add content. This is the form that the user will see if
 * they go to node/add/external-link.
 *
 * You can get fancy with this form, or you can just punt
 * and return the default form that node_content will provide.
 */
function external_link_d7_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Callback that builds our content and returns it to the browser.
 *
 * This callback comes from hook_menu().
 *
 * @return array
 *   A renderable array showing a list of our nodes.
 *
 * @see node_load()
 * @see node_view()
 * @see external_link_d7_field_formatter_view()
 */
function external_link_d7_page() {
  // We'll start building a renderable array that will be our page.
  // For now we just declare the array.
  $renderable_array = array();
  // We query the database and find all of the nodes for the type we defined.
  $sql = 'SELECT nid FROM {node} n WHERE n.type = :type AND n.status = :status';
  $result = db_query($sql,
    array(
      ':type' => 'external_link_d7',
      ':status' => 1,
    )
  );
  $renderable_array['explanation'] = array(
    '#markup' => t("External Link nodes you've created will be displayed here. Note that the color fields will be displayed differently in this list, than if you view the node normally. Click on the node title to see the difference. This is a result of using our 'external_link_d7_list' node view type."),
  );
  // Loop through each of our external_link_d7 nodes and instruct node_view
  // to use our "external_link_d7_list" view.
  // http://api.drupal.org/api/function/node_load/7
  // http://api.drupal.org/api/function/node_view/7
  foreach ($result as $row) {
    $node = node_load($row->nid);
    $renderable_array['node_list'][] = node_view($node, 'external_link_d7_list');
  }
  return $renderable_array;
}

/**
 * Implements hook_entity_info_alter().
 *
 * We need to modify the default node entity info by adding a new view mode to
 * be used in functions like node_view() or node_build_content().
 */
function external_link_d7_entity_info_alter(&$entity_info) {
  // Add our new view mode to the list of view modes...
  $entity_info['node']['view modes']['external_link_d7_list'] = array(
    'label' => t('External Link List'),
    'custom settings' => TRUE,
  );
}


/**
 * Implements hook_field_formatter_info().
 */
function external_link_d7_field_formatter_info() {
  return array(
//    'external_link_d7_colors' => array(
//      'label' => t('Node Example Color Handle'),
//      'field types' => array('text'),
//    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 * @todo: We need to provide a formatter for the colors that a user is allowed
 * to enter during node creation.
 */
function external_link_d7_field_formatter_view($object_type, $object, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'external_link_d7_colors':
//      foreach ($items as $delta => $item) {
//        $element[$delta]['#type'] = 'markup';
//        $color = $item['safe_value'];
//        $element[$delta]['#markup'] = theme('external_link_d7_color', array('color' => $color));
//      }
      break;
  }

  return $element;
}

/**
 * Implements hook_theme().
 *
 * This lets us tell Drupal about our theme functions and their arguments.
 */
//function external_link_d7_theme($existing, $type, $theme, $path) {
//  return array(
//    'external_link_d7_color' => array(
//      'variables' => array('color' => NULL),
//    ),
//  );
//}

/**
 * Implements hook_help().
 */
function external_link_d7_help($path, $arg) {
  switch ($path) {
    case 'admin/structure/external_link_d7':
      return "<p>" . t("The Node Example module provides a custom node type.
        You can create new Example Node nodes using the <a href='!nodeadd'>node add form</a>.",
        array('!nodeadd' => url('node/add/external-link'))) . "</p>";
  }
}

/**
 * A custom theme function.
 *
 * By using this function to format our node-specific information, themes
 * can override this presentation if they wish.  This is a simplifed theme
 * function purely for illustrative purposes.
 */
function theme_external_link_d7_color($variables) {
  $output = '<span style="background-color: #ccc; padding: 1em; margin-bottom: 1em; float: left; color: ' . $variables['color'] . '">' . $variables['color'] . '</span>';
  return $output;
}

/**
 * Define the fields for our content type.
 *
 * This big array is factored into this function for readability.
 *
 * @return array
 *   An associative array specifying the fields we wish to add to our
 *   new node type.
 */
function _external_link_d7_installed_fields() {
    return array(
        'field_link' => array(
            'translatable' => '0',
            'entity_types' => array(),
            'settings' => array(
                'attributes' => array(
                    'target' => 'default',
                    'class' => '',
                    'rel' => '',
                ),
                'url' => 0,
                'title' => 'optional',
                'title_value' => '',
                'title_maxlength' => 128,
                'enable_tokens' => 1,
                'display' => array(
                    'url_cutoff' => 80,
                ),
            ),
            'storage' => array(
                'type' => 'field_sql_storage',
                'settings' => array(),
                'module' => 'field_sql_storage',
                'active' => '1',
                'details' => array(
                    'sql' => array(
                        'FIELD_LOAD_CURRENT' => array(
                            'field_data_field_link' => array(
                                'url' => 'field_link_url',
                                'title' => 'field_link_title',
                                'attributes' => 'field_link_attributes',
                            ),
                        ),
                        'FIELD_LOAD_REVISION' => array(
                            'field_revision_field_link' => array(
                                'url' => 'field_link_url',
                                'title' => 'field_link_title',
                                'attributes' => 'field_link_attributes',
                            ),
                        ),
                    ),
                ),
            ),
            'foreign keys' => array(),
            'indexes' => array(),
            'field_name' => 'field_link',
            'type' => 'link_field',
            'module' => 'link',
            'active' => '1',
            'locked' => '0',
            'cardinality' => '1',
            'deleted' => '0',
            'columns' => array(
                'url' => array(
                    'type' => 'varchar',
                    'length' => 2048,
                    'not null' => FALSE,
                    'sortable' => TRUE,
                ),
                'title' => array(
                    'type' => 'varchar',
                    'length' => 255,
                    'not null' => FALSE,
                    'sortable' => TRUE,
                ),
                'attributes' => array(
                    'type' => 'text',
                    'size' => 'medium',
                    'not null' => FALSE,
                ),
            ),
        )
    );

}

/**
 * Define the field instances for our content type.
 *
 * The instance lets Drupal know which widget to use to allow the user to enter
 * data and how to react in different view modes.  We are going to display a
 * page that uses a custom "external_link_d7_list" view mode.  We will set a
 * cardinality of three allowing our content type to give the user three color
 * fields.
 *
 * This big array is factored into this function for readability.
 *
 * @return array
 *   An associative array specifying the instances we wish to add to our new
 *   node type.
 */
function _external_link_d7_installed_instances() {
  return array(
      'field_link' => array(
          0 => array(
              'label' => 'Link',
              'widget' => array(
                  'weight' => '31',
                  'type' => 'link_field',
                  'module' => 'link',
                  'active' => 0,
                  'settings' => array(),
              ),
              'settings' => array(
                  'absolute_url' => 1,
                  'validate_url' => 1,
                  'url' => 0,
                  'title' => 'none',
                  'title_value' => '',
                  'title_label_use_field_label' => 0,
                  'title_maxlength' => '128',
                  'enable_tokens' => 1,
                  'display' => array(
                      'url_cutoff' => '80',
                  ),
                  'attributes' => array(
                      'target' => 'default',
                      'rel' => '',
                      'configurable_class' => 0,
                      'class' => '',
                      'configurable_title' => 0,
                      'title' => '',
                  ),
                  'rel_remove' => 'default',
                  'user_register_form' => FALSE,
              ),
              'display' => array(
                  'default' => array(
                      'label' => 'above',
                      'type' => 'link_default',
                      'settings' => array(),
                      'module' => 'link',
                      'weight' => 2,
                  ),
                  'full' => array(
                      'label' => 'above',
                      'type' => 'field_redirection',
                      'weight' => '0',
                      'settings' => array(
                          'code' => '301',
                          '404_if_empty' => FALSE,
                          'page_restrictions' => 0,
                          'pages' => '',
                      ),
                      'module' => 'field_redirection',
                  ),
                  'teaser' => array(
                      'type' => 'hidden',
                      'label' => 'above',
                      'settings' => array(),
                      'weight' => 0,
                  ),
                  'external_link_d7_list' => array(
                      'type' => 'hidden',
                      'label' => 'above',
                      'settings' => array(),
                      'weight' => 0,
                  ),
              ),
              'required' => 1,
              'description' => '',
              'default_value' => NULL,
              'field_name' => 'field_link',
              'entity_type' => 'node',
              'bundle' => 'external_link_d7',
              'deleted' => '0',
          ),
      ),
  );
}

/**
 * @} End of "defgroup external_link_d7".
 */
